### ISSUE TITLE
problem understanding the age_table

### ISSUE THREAD

**Issue by ynma-hanvo** [HKUST-Aerial-Robotics/open_quadtree_mapping#35]
hi,   I have problem understanding the code  in device kernel function:  image_to_cost
the age_table_devptr is used,  but it seems is never updated .  
and also what is the purpose of : 
const int my_frame_id = (float) this_age / 10.0 * (float) frame_id;
as what i understand, 
frame_id is for one of  the previous 5 frames used for cost computation

**Comment by WANG-KX** [comment]
Hi,
It has been a long long time since the project finished.
```this_age``` means how many frames the pixel has been observed, and we evenly divided it into 10 folds and calculate the cost volume. Say the pixel age is 20, and we want to calculate the cost volume of frames 2, 4, 6, 8, 10, 12 .... ```frame_id``` is the idx of these used frames.
